import { useEffect, useRef, useState, type ReactNode, type CSSProperties } from 'react';
import { motion, useScroll } from 'framer-motion';
import { ArrowRight, Check, ShieldCheck, ClipboardCheck, FileCheck2, Layers3, Compass, BadgeCheck, Quote, X, Building2 } from 'lucide-react';
import { siteContent as c } from '../../content';
import { HeroSlider } from './HeroSlider';
import { AnimatedValue } from './AnimatedValue';
import { RevealHeading } from './RevealHeading';
import { ButtonLabel } from './ButtonLabel';
import { aboutImage, aboutImageAlt, getServiceImage } from '../../serviceImage';
import './service-image.css';
import { businessContent } from '../../businessContent';

function Section({ id, tone = '', children }: { id?: string; tone?: string; children: ReactNode }) {
  return <section id={id} className={`section ${tone}`}><div className="container">{children}</div></section>;
}
function Heading({ label, title, text }: { label: string; title: string; text?: string }) {
  return <div className="section-heading"><span className="eyebrow">{label}</span><RevealHeading text={title} />{text && <p>{text}</p>}</div>;
}
function Points({ items }: { items: readonly string[] }) { return <ul className="check-list">{items.map(x => <li key={x}><Check size={18} aria-hidden="true" />{x}</li>)}</ul>; }
export function ScrollProgress() { const { scrollYProgress } = useScroll(); return <motion.div className="scroll-progress" style={{ scaleX: scrollYProgress }} aria-hidden="true" />; }
export function HeroSection() { return <HeroSlider />; }
export function TrustStrip() { return <section className="stats-floating-area" aria-label="Company statistics"><div className="container"><div className="stats-box">{c.proofPoints.map(x => <div className="stat-item" key={x.label}><strong><AnimatedValue value={x.value} /></strong><span>{x.label}</span></div>)}<p className="stats-note">{c.metricsNote}</p></div></div></section>; }
export function AboutSection({ dedicated = false }: { dedicated?: boolean }) { return <Section id="about"><div className="split-layout"><div className="about-image"><img className={dedicated ? 'shared-service-image' : undefined} src={dedicated ? aboutImage : c.about.image} alt={dedicated ? aboutImageAlt : c.about.imageAlt} loading="lazy" width="650" height="530" /></div><div><Heading label={c.about.eyebrow} title={c.about.title} text={c.about.description} /><p>{c.about.secondParagraph}</p><Points items={c.about.points} /><a href="/bizsafe" className="button-primary"><ButtonLabel>More About Our Services</ButtonLabel><ArrowRight size={18} /></a></div></div></Section>; }
export function FeaturedServices({ only, preview = false }: { only?: string; preview?: boolean }) { return <Section id="services" tone="featured-services dark-section"><Heading label="Our Services" title="BizSAFE Support for Your Business" />{!only && <nav className="service-tabs" aria-label="BizSAFE services">{c.featuredServices.map(s => <a href={s.id === 'bizsafe' ? '/bizsafe' : `/bizsafe-${s.id}`} key={s.id}>{s.title}<ArrowRight size={16} /></a>)}</nav>}{c.featuredServices.filter(s => !only || s.id === only).map((s,i) => <div id={`feature-${s.id}`} className={`split-layout feature-row ${i % 2 ? 'reverse' : ''}`} key={s.id}><img className={`feature-image ${only ? 'shared-service-image' : ''}`} src={only ? getServiceImage(only === 'bizsafe' ? '/bizsafe' : '/bizsafe-' + only).src : s.image} alt={only ? getServiceImage(only === 'bizsafe' ? '/bizsafe' : '/bizsafe-' + only).alt : s.alt} loading="lazy" width="640" height="460" /><div><Heading label={s.label} title={s.title} text={s.description} />{!preview && <Points items={s.points} />}<a className="button-primary button-gold" href={preview ? (s.id === 'bizsafe' ? '/bizsafe' : `/bizsafe-${s.id}`) : '/contact'}><ButtonLabel>{s.cta}</ButtonLabel><ArrowRight size={18} /></a></div></div>)}</Section>; }
export function MetricsSection() { return <Section tone="metrics-section pale-section"><div className="split-layout"><div><Heading label="Achievements" title="Progress Built Around Your Business" /><div className="metrics-grid">{c.proofPoints.map(x => <div key={x.label}><strong><AnimatedValue value={x.value} /></strong><span>{x.label}</span></div>)}</div><p className="section-note">{c.metricsNote}</p></div><div className="achievement-image"><img src="/kmk-engineering.jpg" alt="Engineer reviewing workplace equipment" loading="lazy" width="640" height="500" /><span><BadgeCheck size={24} aria-hidden="true" />Engineering & Safety Support</span></div></div></Section>; }
const icons = { shield: ShieldCheck, clipboard: ClipboardCheck, file: FileCheck2, layers: Layers3, compass: Compass, check: BadgeCheck };
export function ServicesSection() { return <Section id="other-services" tone="dark-section other-services"><Heading label="Other Services" title="Beyond BizSAFE: Engineering & Business Support" /><div className="services-grid">{c.services.map(s => { const Icon = icons[s.icon as keyof typeof icons]; return <article className="service-card" key={s.id} id={s.id === 'engineering' ? 'engineering' : undefined}><div className="service-icon"><Icon size={32} aria-hidden="true" /></div><h3>{s.title}</h3><p>{s.description}</p><a href={s.href}>{c.labels.learnMore}<ArrowRight size={18} /></a></article>; })}</div><div className="iso-panel" id="iso"><h3>ISO Management-System Support</h3><p>Discuss your chosen standard, existing practices and certification-readiness requirements.</p><div className="iso-grid">{c.isoStandards.map(s => <article id={s.id} key={s.id}><Layers3 size={24} aria-hidden="true" /><h4>{s.title}</h4><p>{s.description}</p><a href={`/${s.id}`}>Explore {s.title}<ArrowRight size={16} /></a></article>)}</div></div><div className="services-grid">{businessContent.map(item => <article className="service-card" key={item.id}><h3>{item.title}</h3><p>{item.paragraphs[0]}</p><a href={`/${item.id}`}>Learn More<ArrowRight size={18}/></a></article>)}<article className="service-card"><h3>Sponsor</h3><p>Technology, software, digital marketing and creative business solutions.</p><a href="/sponsor">Learn More<ArrowRight size={18}/></a></article></div></Section>; }
export function WhySection() { return <Section id="why-kmk" tone="pale-section"><Heading label={c.why.eyebrow} title={c.why.title} text={c.why.description} /><div className="why-grid">{c.why.benefits.map((b,i) => { const Icon = Object.values(icons)[i]; return <article key={b.title}><div className="why-icon"><Icon size={34} aria-hidden="true" /></div><h3>{b.title}</h3><p>{b.body}</p></article>; })}</div></Section>; }
export function SafetyStatement() { return <Section id="certification" tone="certification-section"><div className="split-layout"><div className="certification-image"><img src={getServiceImage('/bizsafe-star').src} alt={getServiceImage('/bizsafe-star').alt} loading="lazy" width="640" height="560" /><div className="certification-badge"><FileCheck2 size={42} aria-hidden="true" /><strong>Ready for the next step</strong><span>Documentation · Implementation · Review</span></div><p className="image-note">KMK consultancy image. Certification is assessed independently.</p></div><div><Heading label={c.compliance.label} title={c.compliance.title} text={c.compliance.description} /><Points items={c.compliance.points} /><div className="cert-stat"><span>Approved certification figures<br />awaiting confirmation</span></div><a href="/contact" className="button-primary"><ButtonLabel>{c.compliance.cta}</ButtonLabel><ArrowRight size={18} /></a></div></div></Section>; }
export function BlogSection() {
  const [article, setArticle] = useState<typeof c.blog[number] | null>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (article) dialog.current?.showModal(); }, [article]);
  return <Section id="blog" tone="pale-section blog-section"><Heading label="Our Blog" title="Insights for Safer Workplaces" /><div className="blog-grid">{c.blog.map(b => <article className="blog-card" key={b.id}><div className="blog-image"><img src={b.image} alt={b.title} loading="lazy" width="440" height="300" /></div><div className="blog-copy"><div className="blog-meta"><span>KMK Insights</span><span>{b.category}</span></div><h3>{b.title}</h3><p>{b.intro}</p><button onClick={() => setArticle(b)} aria-haspopup="dialog">Continue Reading<ArrowRight size={18} /></button></div></article>)}</div><dialog ref={dialog} className="article-dialog" onClose={() => setArticle(null)} onClick={event => { if (event.target === event.currentTarget) dialog.current?.close(); }}><button className="dialog-close" onClick={() => dialog.current?.close()} aria-label="Close article" autoFocus><X size={22} /></button>{article && <><span className="eyebrow">{article.category}</span><h2>{article.title}</h2><p>{article.body}</p><a className="button-primary" href="/contact" onClick={() => dialog.current?.close()}><ButtonLabel>Discuss with KMK</ButtonLabel><ArrowRight size={18} /></a></>}</dialog></Section>;
}
export { TestimonialSlider as TestimonialSection } from "./TestimonialSlider";
export function PartnersSection() {
  const windowRef=useRef<HTMLDivElement>(null), groupRef=useRef<HTMLDivElement>(null);
  const [geometry,setGeometry]=useState({width:1224,copies:3}),[running,setRunning]=useState(false);
  useEffect(()=>{
    const window=windowRef.current,group=groupRef.current;if(!window||!group)return;
    const measure=()=>{const width=group.getBoundingClientRect().width;if(width)setGeometry({width,copies:Math.max(2,Math.ceil(window.clientWidth/width)+1)});};
    measure();const resize=new ResizeObserver(measure);resize.observe(window);resize.observe(group);
    const observer=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>setRunning(entries.some(e=>e.isIntersecting))):null;if(observer)observer.observe(window);else setRunning(!document.hidden);
    const visibility=()=>setRunning(!document.hidden&&window.getBoundingClientRect().bottom>0&&window.getBoundingClientRect().top<innerHeight);document.addEventListener('visibilitychange',visibility);
    return()=>{resize.disconnect();observer?.disconnect();document.removeEventListener('visibilitychange',visibility);};
  },[]);
  return <Section tone="partners-section dark-section"><Heading label="Our Partners" title={c.partnersMarquee.heading}/><div ref={windowRef} className="partner-window" data-running={running} tabIndex={0} aria-label="Client and partner logo placeholders. Hover or focus to pause."><div className="partner-track" style={{'--partner-width':geometry.width+'px','--partner-duration':geometry.width/40+'s'} as CSSProperties}>{Array.from({length:geometry.copies},(_,group)=><div ref={group===0?groupRef:undefined} className="partner-group" key={group} aria-hidden={group>0} inert={group>0}>{c.partnersMarquee.items.map((x,i)=><div key={i}><Building2 size={28} aria-hidden="true"/><span>{x}</span></div>)}</div>)}</div></div><p className="section-note">{c.partnersMarquee.note}</p></Section>;
}
