import { AnimatePresence, motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Pause, Play, Quote } from 'lucide-react';
import { siteContent as c } from '../../content';
import { useCarousel } from '../../hooks/useCarousel';
import { motionTiming } from '../../lib/animation';
import { RevealHeading } from './RevealHeading';
export function TestimonialSlider() {
 const carousel=useCarousel(c.testimonial.slides.length,motionTiming.testimonial.intervalMs);
 const item=c.testimonial.slides[carousel.active];
 return <section className="section dark-section testimonials-section"><div className="container"><div className="section-heading"><span className="eyebrow">{c.testimonial.label}</span><RevealHeading text={c.testimonial.heading}/></div><div className="testimonial-slider" tabIndex={0} aria-roledescription="carousel" aria-label="KMK feedback placeholders" {...carousel.interactionProps}><div className="testimonial-stage">{c.testimonial.slides.map((slide,i)=><article className="testimonial-card testimonial-sizer" aria-hidden="true" inert key={i}><Quote size={44}/><span className="placeholder-tag">Placeholder</span><blockquote>{slide.placeholder}</blockquote><p>{slide.attribution}</p></article>)}<AnimatePresence initial={false} mode="popLayout"><motion.article key={carousel.active} className="testimonial-card" role="group" aria-label={'Testimonial '+(carousel.active+1)} initial={{opacity:carousel.reduced?1:0,x:carousel.reduced?0:60*carousel.direction.current}} animate={{opacity:1,x:0}} exit={{opacity:0,x:carousel.reduced?0:-60*carousel.direction.current}} transition={{duration:carousel.reduced?0:motionTiming.testimonial.transition,ease:motionTiming.ease}}><Quote size={44} aria-hidden="true"/><span className="placeholder-tag">Placeholder</span><blockquote>{item.placeholder}</blockquote><p>{item.attribution}</p></motion.article></AnimatePresence></div><div className="testimonial-controls"><button onClick={()=>carousel.move(-1)} aria-label="Previous testimonial"><ArrowLeft size={18}/></button>{c.testimonial.slides.map((_,i)=><button className={'hero-dot '+(carousel.active===i?'active':'')} key={i} aria-label={'Show testimonial '+(i+1)} aria-current={carousel.active===i?'true':undefined} onClick={()=>carousel.change(i)}/>)}<button onClick={()=>carousel.move(1)} aria-label="Next testimonial"><ArrowRight size={18}/></button><button onClick={()=>carousel.setPaused(p=>!p)} aria-label={carousel.paused?'Play testimonials':'Pause testimonials'}>{carousel.paused?<Play size={16}/>:<Pause size={16}/>}</button></div></div><p className="section-note">{c.testimonial.note}</p></div></section>;
}
