export const siteContent = {
 labels: { servicesCta: 'Explore Our Services', learnMore: 'Learn More', projectCta: 'Discuss a similar requirement', consultationCta: 'Request Consultation' },
 trustPoints: ["BizSAFE & WSH", "Risk Management Support", 'Built Around Your Workplace', 'Singapore Businesses'],
 servicesIntro: { label: 'Our Services', title: "BizSAFE, ISO & Safety Support for Your Business", text: "Explore workplace safety, engineering and management-system support, from identifying hazards to preparing documentation and reviewing readiness for assessment." },
 metricsIntro: { label: 'Experience & Achievements', title: 'Supporting progress. Building confidence.', note: 'Company figures are placeholders pending verification.' },
 industriesIntro: { label: 'Industries We Support', title: 'Guidance grounded in your industry', text: "Different environments call for different controls: construction involves changing sites and contractors; manufacturing involves machinery and process hazards; marine operations involve vessel and dockside work; logistics involves vehicles and material handling. Engineering, facilities management and industrial operations bring equipment, maintenance and workplace coordination needs. KMK discusses the activities at your site so safety documentation and compliance preparation reflect the work involved." },
 processIntro: { label: 'Our Process', title: "A clear path from assessment to audit readiness", text: "A practical sequence for engineering, safety and management-system work, with responsibilities and preparation agreed at each stage." },
 projectsIntro: { label: 'Projects & Experience', title: 'Practical support in real work environments', text: 'Project details below are editable placeholders awaiting approved case studies.' },
 compliance: { label: 'Compliance & Certification Support', title: "From documentation to certification readiness.", description: "Prepare for assessment with documents that match your workplace. KMK can review risk assessments, system procedures and implementation records, help identify gaps and plan corrective actions. Your team remains responsible for applying the controls; relevant independent auditors or certification bodies assess the evidence.", cta: 'Discuss Your Requirements' },
 partnersIntro: { label: 'Client & Partner Recognition' },
 featuredServices: [
 { id: 'bizsafe', label: 'Workplace Safety', title: 'BizSAFE & WSH Consultancy', description: "BizSAFE develops workplace safety capability through management commitment, risk management and practical implementation. KMK supports businesses preparing for relevant BizSAFE requirements, from workplace review and documentation to readiness checks. The aim is a working safety system with clear responsibilities, effective controls and records that reflect actual operations.", image: '/kmk-safety-hero.jpg', alt: 'Safety professional reviewing an industrial workplace', points: ["Level 3: understand work activities, identify hazards, assess risk and determine controls. Prepare the Risk Management Plan, guide implementation and review evidence before an independent risk management audit.", "Level 4: plan a WSH Management System with policies, procedures, responsibilities and workplace controls. Organise monitoring records, management guidance and internal readiness review to support a consistent safety approach.", "STAR: review management-system maturity, documented WSH processes and alignment with recognised safety-management standards. Plan internal reviews, management review records and audit preparation, with ongoing improvement and surveillance needs considered.", "WSH support: review hazards and safety arrangements with management and staff. Discuss documentation, implementation, corrective actions and compliance gaps; keep risk controls and records current as activities change."], cta: 'Discuss Your Safety Needs' },
 { id: 'iso', label: 'Management Systems', title: 'ISO Consultancy & Documentation', description: "ISO management systems help organisations manage quality, environmental responsibilities and occupational health and safety in a consistent way. KMK offers consultancy and certification-readiness support, beginning with your objectives, existing practices and chosen standard. Agree the scope, develop usable documentation and put procedures into practice before independent certification assessment.", image: '/kmk-consultation.jpg', alt: 'Consultant reviewing workplace plans', points: ["ISO 9001: strengthen quality management through consistent processes, customer requirements and performance review. Prepare quality policies, procedures and records; assess gaps and plan implementation, internal audits and management review.", "ISO 14001: organise environmental management around your operations and impacts. Review gaps, environmental aspects and controls; prepare policies, procedures and monitoring records for implementation, internal audit and management review.", "ISO 45001: structure occupational health and safety management around hazards, worker participation and risk controls. Develop policies, responsibilities and records, then plan implementation, internal audit and management review preparation.", "Readiness support: review the agreed system, follow up corrective actions and organise evidence before the certification audit. Plan continuing reviews and surveillance preparation. Independent certification bodies carry out certification assessment."], cta: 'Plan Your Next Step' },
 { id: 'engineering', label: 'Technical Guidance', title: 'Engineering Consultancy', description: "Engineering consultancy helps businesses understand technical requirements in the context of their site, equipment and processes. KMK can discuss technical reviews, safety integration and relevant documentation, then agree practical options and a proportionate project scope. Share your drawings, site information and objectives so the next steps can be considered.", image: '/kmk-engineering.jpg', alt: 'Engineer inspecting industrial equipment', points: ["Review technical questions, site conditions and operational constraints before proposing a practical approach.", "Consider workplace processes, equipment interfaces and associated safety risks when reviewing options.", "Discuss drawings, technical records and supporting documentation where relevant to the agreed engineering scope.", "Connect technical recommendations with project priorities, risk controls and compliance preparation; confirm specialist requirements before proceeding."], cta: 'Speak About Your Project' }
 ],
  company: {
    legalName: 'KMK Engineering & Consultancy Pte Ltd',
    shortName: 'KMK Engineering & Consultancy',
    monogram: 'KMK',
    tagline: 'Engineering clarity. Safer workplaces.',
    phone: '[Phone Number]',
    email: '[Email Address]',
    address: '[Office Address]',
    projects: '[XX+ Projects]',
    years: '[XX Years]',
    clients: '[XX+ Businesses]',
    responseTime: '[Response Time]',
    copyright: `© ${new Date().getFullYear()} KMK Engineering & Consultancy Pte Ltd. All rights reserved.`,
  },
  navigation: [
    { label: 'Home', href: '#home' },
    { label: 'About', href: '#about' },
    { label: 'Services', href: '#services' },
    { label: 'Industries', href: '#industries' },
    { label: 'Why KMK', href: '#why-kmk' },
    { label: 'Projects', href: '#projects' },
    { label: 'FAQ', href: '#faqs' },
    { label: 'Contact', href: '#contact' },
  ],
  heroSlides: [
    {
      eyebrow: "BizSAFE & Workplace Safety",
      title: "Build Safer Workplaces.<br /><em>Strengthen Compliance.</em>",
      description: "Practical support for BizSAFE, Workplace Safety & Health, risk management and compliance, with engineering guidance shaped around your operations.",
      image: '/kmk-safety-hero.jpg',
      imageAlt: 'A safety professional reviewing a workplace inspection in an industrial facility',
      button: 'Get a Free Consultation',
    },
    {
      eyebrow: "BizSAFE Level 3 & Level 4",
      title: "From Risk Management to <em>Audit Readiness.</em>",
      description: "Prepare risk assessments, Risk Management Plans and WSH management systems, with documentation and implementation guidance before assessment.",
      image: '/kmk-consultation.jpg',
      imageAlt: 'An engineer discussing risk assessment drawings at a worksite',
      button: 'Get a Free Consultation',
    },
    {
      eyebrow: "BizSAFE STAR & ISO",
      title: "Advance Your Safety <em>Management System.</em>",
      description: "Structured ISO consultancy and BizSAFE STAR preparation to strengthen your systems, review performance and plan continual workplace safety improvement.",
      image: '/kmk-engineering.jpg',
      imageAlt: 'An engineer inspecting equipment at a modern industrial facility',
      button: 'Get a Free Consultation',
    },
  ],
  proofPoints: [
    { value: '[XX+]', label: 'Projects supported' },
    { value: '[XX]', label: 'Years of experience' },
    { value: '[XX+]', label: 'Businesses supported' },
    { value: '[Response Time]', label: 'Typical response' },
  ],
  about: {
    eyebrow: 'About KMK',
    title: "Engineering & Safety Support Built Around Your Workplace",
    description: "KMK Engineering & Consultancy Pte Ltd provides practical engineering, workplace safety and compliance-readiness support for Singapore businesses. From risk assessments and Risk Management Plans to BizSAFE preparation and ISO management systems, we help you connect documentation with the way work is actually carried out.",
    points: [
      "Understand your operations, management commitment and target requirements before agreeing the consultancy scope.",
      "Develop workplace-specific risk controls, safety procedures and supporting records your team can use.",
      "Support implementation, review gaps and prepare evidence for independent assessment and continual improvement.",
    ],
    image: '/kmk-consultation.jpg',
    imageAlt: 'A consultant and site professional reviewing a safety plan together',
    captionTitle: 'Built around your workplace',
    captionText: "Risk awareness. Practical preparation.",
  },
  services: [
    {
      id: 'bizsafe',
      number: '01',
      icon: 'shield',
      title: 'BizSAFE & WSH consultancy',
      description: "For businesses starting or progressing through BizSAFE. Review safety practices, management commitment and gaps; plan Level 3, Level 4 or STAR preparation around your workplace.",
      href: '#contact',
    },
    {
      id: 'risk',
      number: '02',
      icon: 'clipboard',
      title: "Risk assessment & RMP",
      description: "Identify hazards in routine and non-routine work, evaluate risk and review existing controls. Record additional measures, owners and review actions in risk assessments and your Risk Management Plan.",
      href: '#contact',
    },
    {
      id: 'documentation',
      number: '03',
      icon: 'file',
      title: 'Safety documentation',
      description: "Prepare workplace-specific Safe Work Procedures, safety policies, emergency procedures, inspection checklists and briefing records. Keep these aligned with risk assessments and implementation evidence.",
      href: '#contact',
    },
    {
      id: 'iso',
      number: '04',
      icon: 'layers',
      title: 'ISO consultancy',
      description: "Plan ISO 9001, ISO 14001 or ISO 45001 systems. Discuss gap assessment, policy and procedure development, implementation, internal audit and management review preparation.",
      href: '#contact',
    },
    {
      id: 'engineering',
      number: '05',
      icon: 'compass',
      title: 'Engineering consultancy',
      description: "Review site, equipment and process requirements alongside safety considerations. Discuss practical technical options, relevant documentation and engineering input for project or compliance needs.",
      href: '#contact',
    },
    {
      id: 'compliance',
      number: '06',
      icon: 'check',
      title: "Compliance & audit readiness",
      description: "Review requirements, supporting records and implementation gaps before assessment. Plan corrective actions and organise evidence for independent auditors, with the scope agreed during consultation.",
      href: '#contact',
    },
  ],
  why: {
    eyebrow: 'Why work with KMK',
    title: 'Why Choose KMK',
    description: "Clear advice and a structured process help your team understand requirements, prepare useful records and keep workplace improvements moving.",
    benefits: [
      { number: '01', title: 'Practical Guidance', body: "Translate safety, engineering and management-system requirements into realistic actions for your workplace." },
      { number: '02', title: 'Industry Understanding', body: "Consider your work activities, people, equipment and site conditions when developing risk controls." },
      { number: '03', title: 'Clear Documentation', body: "Prepare records that reflect actual operations and help staff explain how procedures are implemented." },
      { number: '04', title: "Structured Process", body: "Agree scope and responsibilities, track preparation and review gaps so your team understands the next step." },
    ],
  },
  engineeringFeature: {
    eyebrow: 'Engineering consultancy',
    title: 'Sound decisions begin with the right questions.',
    description: 'Technical requirements can feel opaque when you are already running a business. We help you work through the detail, understand your options and plan a considered way forward.',
    image: '/kmk-engineering.jpg',
    imageAlt: 'An engineer checking systems and equipment during a facility walk-through',
    linkLabel: 'Discuss an engineering requirement',
  },
  milestones: {
    heading: 'A steady partner for the work ahead.',
    items: [
      { value: '[XX+]', label: 'Projects supported' },
      { value: '[XX]', label: 'Years of experience' },
      { value: '[XX+]', label: 'Business relationships' },
      { value: '[XX]', label: 'Service areas' },
    ],
  },
  standardsMarquee: {
    heading: 'Frameworks we can help you navigate',
    note: 'Framework names shown for information only. No accreditation or certification is implied.',
    items: ['BizSAFE', 'Workplace Safety & Health', 'Risk Assessment', 'ISO Management Systems', 'Safety Documentation', 'Engineering Consultancy', 'Compliance Support'],
  },
  partnersMarquee: {
    heading: 'Businesses We Support',
    note: 'Replace these editable placeholders only with approved names or logos.',
    items: ['[Client Logo 1]', '[Partner Logo 1]', '[Client Logo 2]', '[Partner Logo 2]'],
  },
  testimonial: {
    label: 'Client perspective', heading: 'What Our Clients Say',
    slides: [
      {
        placeholder: '[Editable testimonial placeholder — replace with an approved client quote before publishing.]',
        attribution: '[Client Name] · [Role / Organisation]',
      },
      {
        placeholder: '[Second editable testimonial placeholder — replace only with a client-approved quote.]',
        attribution: '[Client Name] · [Role / Organisation]',
      },
    ],
    note: 'Placeholder only. Publish a testimonial only with the client’s approval.',
  },
  faqs: [
    {"question":"What is BizSAFE?","answer":"BizSAFE is a Singapore programme for developing workplace safety and health capability. It links management commitment with risk management, implementation and stronger safety systems. KMK supports businesses in preparing for relevant BizSAFE requirements through workplace review, documentation and practical guidance. Begin by discussing your current status, activities and intended level."},
    {"question":"What is required for BizSAFE Level 3?","answer":"Level 3 focuses on implementing risk management in the workplace. Preparation includes understanding activities, identifying hazards, assessing risks, selecting controls and documenting a Risk Management Plan. Your team needs to implement the measures and maintain supporting records before an independent risk management audit. KMK can discuss staff and management guidance, documentation review and corrective-action preparation where gaps are identified."},
    {"question":"What is the difference between BizSAFE Level 3 and Level 4?","answer":"Level 3 centres on workplace risk management implementation. Level 4 builds capability to develop a Workplace Safety and Health Management System (WSHMS) implementation plan. Policies, procedures, responsibilities, workplace controls and monitoring bring a more systematic approach to safety. KMK can help review existing arrangements, plan documentation and discuss the preparation appropriate to your target level."},
    {"question":"What is BizSAFE STAR?","answer":"STAR is the highest level of recognition in the BizSAFE programme and involves a more mature approach to workplace safety management. Preparation considers systematic WSH processes, implementation evidence and relevant recognised safety-management standards. KMK can discuss system gaps, internal review, management review records and independent audit readiness. Continuing monitoring and improvement help keep the system useful after assessment."},
    {"question":"How long does BizSAFE preparation normally take?","answer":"The preparation period depends on your target level, workplace activities, team availability and existing documentation. Developing a new system generally involves more work than reviewing established procedures and records. Training, implementation and independent assessment schedules also affect timing. Share your current position and target date with KMK so the work needed can be discussed; no fixed completion period is promised."},
    {"question":"Does KMK support Risk Assessment preparation?","answer":"KMK can discuss hazard identification, risk evaluation and review of existing controls with your workplace team. Additional measures should consider the hierarchy of controls, from removing hazards and changing processes to engineering controls, administrative measures and personal protective equipment. Record risk ratings, control owners and follow-up actions in a risk register. Review the assessment when work changes or incidents reveal new concerns."},
    {"question":"Can KMK help prepare safety documentation?","answer":"Support can cover risk assessments, Safe Work Procedures, Risk Management Plans, safety policies and procedures, inspection checklists, emergency arrangements and training or briefing records, where appropriate to the agreed scope. Documents should describe how your business actually works, with responsibilities and implementation evidence clearly recorded. Share existing materials first so useful records can be retained and gaps identified."},
    {"question":"What does WSH consultancy involve?","answer":"Workplace Safety and Health consultancy reviews how risks are managed across your activities, people and workplace. KMK can discuss safety and hazard reviews, documentation, implementation support, management-system guidance and readiness assessments. Findings can be used to plan corrective actions and clarify compliance needs. The scope is agreed around your operations, with follow-up focused on whether controls are being applied in practice."},
    {"question":"Does KMK support ISO 45001 preparation?","answer":"KMK can discuss consultancy and certification-readiness support for an occupational health and safety management system. Preparation may include gap assessment, policy and procedure development, worker participation, responsibilities, risk controls and implementation records. Internal audit and management review preparation help identify improvements before an independent certification audit. Confirm your operations, chosen standard and required scope during consultation."},
    {"question":"What is the difference between BizSAFE and ISO 45001?","answer":"BizSAFE is a Singapore workplace safety capability programme; ISO 45001 is an international occupational health and safety management-system standard. Their purposes and assessment routes differ, although safety policies, risk controls and implementation records can overlap. When planning STAR and ISO preparation together, KMK can discuss coordinated documentation and readiness work against the relevant requirements. Certification does not replace day-to-day workplace safety responsibilities."},
    {"question":"What does ISO 9001 consultancy cover?","answer":"ISO 9001 concerns quality management: consistent processes, customer requirements, performance review and improvement. KMK can discuss gaps in current practices, quality policies, procedures, responsibilities and supporting records. Implementation, internal audit preparation and management review help establish whether the system is working before an independent certification audit. The aim is a usable management system with evidence of how quality is managed."},
    {"question":"What does ISO 14001 consultancy cover?","answer":"ISO 14001 concerns environmental management, including how activities affect the environment and how those impacts are controlled. KMK can discuss gap assessment, environmental aspects, policies, procedures and monitoring records suited to your operations. Implementation, internal audit and management review preparation support certification readiness and improvement. The agreed scope determines which sites, activities and records are included."},
    {"question":"Does KMK support audit readiness?","answer":"KMK can review documents and implementation evidence, help identify gaps and discuss corrective actions before independent assessment. Useful records may include risk controls, inspections, staff briefings, internal review findings and management review actions. Your team should be able to explain the procedures and show that controls are in use. Consultancy helps preparation; the relevant independent auditor or certification body makes the assessment decision."},
    {"question":"What information is needed before starting?","answer":"Share your business activities, sites, workforce arrangements and current BizSAFE or ISO status, along with your target outcome and dates. Existing risk assessments, safety procedures, technical drawings, training records and earlier audit findings help clarify the starting point. KMK can then discuss priorities, required documents, responsibilities and a suitable consultancy scope without assuming every business needs the same package."},
    {"question":"How do I start a consultation?","answer":"Use the consultation form to describe your workplace and the engineering, safety, BizSAFE, ISO or compliance requirement you need help with. Include your company details, current status and objectives. The form currently prepares an email draft rather than sending automatically; the site owner must replace the email placeholder before it can be used to contact KMK. Review the draft in your email app before sending."}
  ],
  contact: {
    eyebrow: "Speak with KMK",
    heading: 'Get a Free Consultation',
    description: "Tell us about your workplace, engineering, safety, BizSAFE, ISO or compliance requirements. Share your current status and objectives so KMK can help you understand the next practical steps.",
    emailLabel: '[Email Address]',
    phoneLabel: '[Phone Number]',
    addressLabel: '[Office Address]',
    formNotice: 'Your message will open as a draft in your email app. It will not be sent automatically.',
  },
  footer: {
    about: "KMK Engineering & Consultancy Pte Ltd provides practical BizSAFE and WSH consultancy, risk assessment, safety documentation, ISO management-system preparation and engineering guidance for Singapore businesses. Discuss your workplace and objectives to agree a suitable scope.",
    quickLinks: [
      { label: 'Home', href: '#home' },
      { label: 'Industries', href: '#industries' },
      { label: 'Projects', href: '#projects' },
      { label: 'Contact', href: '#contact' },
      { label: 'About KMK', href: '#about' },
      { label: 'Our services', href: '#services' },
      { label: 'Why KMK', href: '#why-kmk' },
      { label: 'Frequently asked questions', href: '#faqs' },
    ],
    services: ['BizSAFE & WSH consultancy', "Risk assessment", 'Safety documentation', 'ISO consultancy', 'Engineering consultancy', "Compliance support"],
    disclaimer: 'Information on this website is general in nature and does not replace advice on your specific obligations.',
  },
  hero: {
    title: 'Engineering Safer. Building Smarter.',
    description: 'Professional Safety, Engineering and Consultancy Solutions for Modern Businesses.',
    image: '/kmk-safety-hero.jpg',
    imageAlt: 'Safety professional reviewing worksite conditions at an industrial facility',
    floatingLabels: ['WORKPLACE SAFETY', 'ENGINEERING SYSTEMS', 'COMPLIANCE SUPPORT'],
  },
  industries: [
    { name: 'Construction', image: '/industry-construction.jpg', alt: 'Construction site and tower cranes at dusk' },
    { name: 'Manufacturing', image: '/industry-manufacturing.jpg', alt: 'Modern manufacturing production floor' },
    { name: 'Marine', image: '/industry-marine.jpg', alt: 'Cargo vessel and cranes at a marine port' },
    { name: 'Logistics', image: '/industry-logistics.jpg', alt: 'Warehouse aisle with logistics equipment' },
    { name: 'Engineering', image: '/kmk-engineering.jpg', alt: 'Engineer inspecting industrial equipment' },
    { name: 'Facilities Management', image: '/kmk-consultation.jpg', alt: 'Facilities professionals reviewing a site plan' },
    { name: 'Industrial Operations', image: '/kmk-safety-hero.jpg', alt: 'Safety professional at an industrial operation' },
  ],
  values: [
    { number: '01', title: 'Practical by design', body: 'Guidance shaped around the work people actually do.' },
    { number: '02', title: 'Safety first', body: 'Protecting people is the foundation of sound engineering.' },
    { number: '03', title: 'Clear communication', body: 'Complex requirements made easier to understand.' },
    { number: '04', title: 'Integrity in every detail', body: 'Honest advice, transparent scope, dependable follow-through.' },
    { number: '05', title: 'Connected thinking', body: 'Safety, compliance and engineering considered together.' },
    { number: '06', title: 'Built for progress', body: 'Better systems support resilient, confident operations.' },
  ],
  workflow: [
    { title: 'Listen', body: "Understand your organisation, workplace activities and objectives." },
    { title: 'Assess', body: "Review practices, records, hazards and compliance needs." },
    { title: 'Plan', body: "Develop a practical action plan and required documentation." },
    { title: 'Implement', body: "Support your team in putting agreed measures into practice." },
    { title: 'Review', body: "Check readiness, address gaps and support continual improvement." },
  ],
  projects: [
    { title: '[Project title]', category: '[Industry / service area]', image: '/kmk-engineering.jpg', alt: 'Editable project image placeholder: industrial engineering environment', status: 'Editable project placeholder' },
    { title: '[Project title]', category: '[Industry / service area]', image: '/kmk-consultation.jpg', alt: 'Editable project image placeholder: consultation at an industrial site', status: 'Editable project placeholder' },
    { title: '[Project title]', category: '[Industry / service area]', image: '/kmk-safety-hero.jpg', alt: 'Editable project image placeholder: workplace safety review', status: 'Editable project placeholder' },
  ],
  safetyMessage: {
    title: 'Safety Is Not Just Compliance. It Is Part of Good Engineering.',
    image: '/kmk-engineering.jpg',
    imageAlt: 'Industrial engineer inspecting workplace systems',
  },
  socials: [
    { label: 'LinkedIn', href: '#contact' },
    { label: 'Instagram', href: '#contact' },
  ],
};
// Internal content placeholders: do not render as active KMK services.
// BCA: [Confirm KMK BCA service scope before publishing.]
// Incorporation: [Confirm KMK company incorporation service availability before publishing.]
// PR application: [Confirm KMK PR application service availability before publishing.]
// Additional ISO topics on the reference site: [Confirm KMK ISO 22000 and ISO 27001 consultancy scope before publishing.]
// Knowledge topics are covered in the existing service copy and FAQs; no new blog section is introduced.
